name: CI/CD Pipeline


on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (app)
        run: |
          docker build -t aceest-fitness-app .

      - name: Build Docker image (test)
        run: |
          docker build -f testdockerfile -t aceest-fitness-test .

      - name: Run Pytest in Docker (test image and copy report)
        run: |
          docker container create --name testcontainer aceest-fitness-test
          docker container start testcontainer
          docker container wait testcontainer
          docker cp testcontainer:/gym/report.xml ./report.xml
          docker container rm testcontainer

      - name: Upload Pytest Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.xml
